name: Trigger auto deployment for container-app-4j2ncd7moztxq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'packages/client/**'
    - '.github/workflows/container-app-4j2ncd7moztxq-AutoDeployTrigger-9c11f2b1-ce73-42b5-88af-c42f566cc7de.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP4J2NCD7MOZTXQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP4J2NCD7MOZTXQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP4J2NCD7MOZTXQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/packages/client 
          registryUrl: containerregistry4j2ncd7moztxq.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP4J2NCD7MOZTXQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP4J2NCD7MOZTXQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-4j2ncd7moztxq
          resourceGroup: cloudsource9108
          imageToBuild: containerregistry4j2ncd7moztxq.azurecr.io/container-app-4j2ncd7moztxq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


